apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-server-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: core-server
  template:
    metadata:
      labels:
        app: core-server
    spec:
      containers:
      - name: core-server-container
        image: traefik/whoami
        # image: httpd:latest
        # image: jnovack/whoami
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod-1
spec:
  containers:
    - name: test-container-1
      image: ubuntu:22.04
      command: ["sleep", "infinity"]

---
# link api-server pods with core-server pods using service
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  type: ClusterIP
  selector:
    app: core-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: external-service
spec:
  type: NodePort
  selector:
    app: core-server
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
